project:
  type: website

website:
  title: "Bauke Brenninkmeijer"
  navbar:
    right:
      - about.qmd
      - resume.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/bauke-brenninkmeijer-40143310b/
      - icon: github
        href: https://www.baukebrenninkmeijer.nl
  favicon: posts/images/favicon.png
  open-graph: true
  google-analytics: UA-55798897-4
format:
  html:
    theme:
      light: [lux, 'styles/theme-light.scss']
      dark: [lux, styles/theme-dark.scss]
    css: styles/styles.scss

execute:
  freeze: auto


