project:
  type: website

website:
  title: "Bauke Brenninkmeijer"
  navbar:
    right:
      - talks.qmd
      - about.qmd
      - resume.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/bauke-brenninkmeijer-40143310b/
      - icon: github
        href: https://github.com/Baukebrenninkmeijer
  favicon: posts/images/favicon.png
  open-graph: true
  google-analytics: G-YG1RDE9BKY
format:
  html:
    theme:
      light: [lux, 'styles/theme-light.scss']
      dark: [lux, styles/theme-dark.scss]
    css: styles/styles.scss

execute:
  freeze: auto


resources:
  - "CNAME.txt"